# Generated by Django 4.1.6 on 2024-04-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_reply_like_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default=None, max_length=280),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='work',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
