# Generated by Django 4.1.6 on 2024-04-15 03:23

from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_user_picture_delete_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='media/media/default.png', null=True, upload_to=network.models.filepath),
        ),
    ]
